### PR TITLE
Include image mime in request

### PR DESCRIPTION
**Pull request by bestlibre**
Fix for #24 . I have tested with a local install of tensorflow-lite-server, it's working. I don't have an instance of deepstack to test against it and I'm not familiar with the test suite to add test. I hope this PR is still usefull.

### CODE REVIEW

**Comment by robmarkcole** [comment]
@bestlibre how did you find that solution? Possibly [here](https://stackoverflow.com/questions/12385179/how-to-send-a-multipart-form-data-with-requests-in-python)

**Comment by bestlibre** [comment]
I found the solution based on the curl command in the readme of tensorflow-lite-server and the documentation of requests. The first part of the solution was with a fixed mime type and then I search how to get the mime type from a byte array which lead me to filetype.

**Comment by robmarkcole** [comment]
Unfortunately on deepstack official this approach raises error: `{'success': False, 'error': 'No valid image file found'}`

You can run deepstack official with:
```
docker run -e VISION-DETECTION=True -v localstorage:/datastore -p 5000:5000 -e API-KEY="" --name deepstack deepquestai/deepstack:cpu-x3-beta
```

**Comment by robmarkcole** [comment]
stale

**Pull request closed without merging**
